"""Persistence port used by application services."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol

from ..discovery.base import DiscoveryCandidate
from ..models import Audit, Business, Contact, Page, Score, Signal, Website


class Repository(Protocol):
    """Storage-agnostic unit of persistence."""

    def initialize(self) -> None: ...
    def transaction(self) -> AbstractContextManager[Repository]: ...
    def add_business(self, business: Business) -> None: ...
    def get_business(self, business_id: str) -> Business | None: ...
    def update_business(self, business: Business) -> None: ...
    def delete_business(self, business_id: str) -> bool: ...
    def add_website(self, website: Website) -> None: ...
    def list_websites(self) -> list[Website]: ...
    def get_website_by_domain(self, canonical_domain: str) -> Website | None: ...
    def add_page(self, page: Page) -> None: ...
    def list_pages(self, audit_id: str) -> list[Page]: ...
    def add_contact(self, contact: Contact) -> None: ...
    def list_contacts(self, audit_id: str) -> list[Contact]: ...
    def add_audit(self, audit: Audit) -> None: ...
    def update_audit(self, audit: Audit) -> None: ...
    def get_audit(self, audit_id: str) -> Audit | None: ...
    def list_audits(self, website_id: str) -> list[Audit]: ...
    def add_signal(self, signal: Signal) -> None: ...
    def list_signals(self, audit_id: str) -> list[Signal]: ...
    def add_score(self, score: Score) -> None: ...
    def get_score(self, audit_id: str, score_type: str) -> Score | None: ...
    def list_scores(self, audit_id: str) -> list[Score]: ...
    def latest_score(self, audit_id: str, score_type: str) -> Score | None: ...
    def add_discovery_candidate(self, candidate: DiscoveryCandidate) -> None: ...
    def list_discovery_candidates(
        self, *, category: str | None = None, location: str | None = None
    ) -> list[DiscoveryCandidate]: ...
